# Generated by Django 3.2.3 on 2021-05-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_inclusao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='situacao',
            field=models.CharField(choices=[('A', 'ADIMPLENTE'), ('I', 'INADIMPLENTE')], default='A', max_length=1),
        ),
    ]
