# Generated by Django 3.2.3 on 2021-05-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20210522_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='descricao',
            new_name='observacao',
        ),
    ]
