# Generated by Django 3.2.3 on 2021-05-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_descricao_cliente_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
